### ISSUE TITLE
设置昵称后图片无法正常显示文字

### ISSUE THREAD

**Issue by Neight99** [fc4soda/gfBadge#1]
我虽然有设置个人昵称以及uid等数据，但是生成的图片里貌似并没有按预期正常显示。
![avatar](https://s2.ax1x.com/2020/03/01/3ge4iQ.png)

**Comment by Neight99** [comment]
解决了，貌似又双叒叕是safari的锅（

**Comment by fc4soda** [comment]
抱歉回复晚了，我前端不太熟，适配性的问题我试试用Babel能不能解决。平时用的是windows和linux上的firefox/chrome，总之很谢谢反馈。我还以为这么个一时兴起的初学向工具没人用呢（热泪盈眶
